version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=jasoncndai@gmail.com
  frontend:
    image: ghcr.io/uoft-utsc-cs-sandbox/frontend-webtama
    container_name: frontend
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=webtama.works
      - LETSENCRYPT_HOST=webtama.works
      - LETSENCRYPT_EMAIL=jasoncndai@gmail.com
    depends_on:
      - backend
    links:
      - backend
  backend:
    image: ghcr.io/uoft-utsc-cs-sandbox/backend-webtama
    container_name: backend
    restart: always
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=api.webtama.works
      - LETSENCRYPT_HOST=api.webtama.works
      - LETSENCRYPT_EMAIL=jasoncndai@gmail.com
    depends_on:
      - sqlite3
  sqlite3:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - /db/:/root/db/
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: unless-stopped
